#!/system/bin/sh
# Written by Draco (tytydraco @ GitHub)

# Log in red
err() {
	if [[ -n "$SIMPLE_LOGGING" ]]
	then
		echo "ERROR $*"
	else
		echo -e " \e[91m*\e[39m $*"
	fi
}

# Log in orange
warn() {
	if [[ -n "$SIMPLE_LOGGING" ]]
	then
		echo "WARNING $*"
	else
		echo -e " \e[93m*\e[39m $*"
	fi
}

# Log in white and continue (unnecessary)
dbg() {
	if [[ -n "$SIMPLE_LOGGING" ]]
	then
		echo "DEBUG $*"
	else
		echo -e " \e[92m*\e[39m $*"
	fi
}

# Safely write value to file
write() {
	# Bail out if file does not exist
	[[ ! -f "$1" ]] && return 1

	# Fetch the current key value
	local curval
	curval="$(cat "$1" 2> /dev/null)"

	# Bail out if value is already set
	if [[ "$curval" == "$2" ]]
	then
		warn "$1: $curval → $2"
		return 0
	fi

	# Write the new value
	if ! echo "$2" > "$1" 2> /dev/null
	then
		err "$1: $curval → $2"
		return 1
	fi

	dbg "$1: $curval → $2"
}

usage() {
	echo -n "Usage: $(basename "$0") [OPTIONS]
Options:
  -p			Parsable logging
  -h			Show usage
"
}

while getopts ":ph" opt; do
	case $opt in
		p)
			SIMPLE_LOGGING=1
			;;
		h)
			usage
			exit 0
			;;
		*)
			usage
			exit 1
			;;
	esac
done
shift $((OPTIND - 1))

# Check for root permissions
if [[ "$(id -u)" -ne 0 ]]
then
	err "No root permissions. Exiting."
	exit 1
fi


# Log the date and time
dbg "Time of execution: $(date)"

# Kernel
write /proc/sys/kernel/perf_cpu_time_max_percent 5
write /proc/sys/kernel/sched_autogroup_enabled 0
write /proc/sys/kernel/sched_child_runs_first 1
write /proc/sys/kernel/sched_tunable_scaling 0
write /proc/sys/kernel/sched_latency_ns 4000000
write /proc/sys/kernel/sched_min_granularity_ns 200000
write /proc/sys/kernel/sched_wakeup_granularity_ns 200000
write /proc/sys/kernel/sched_migration_cost_ns 5000000
write /proc/sys/kernel/sched_min_task_util_for_colocation 0
write /proc/sys/kernel/sched_nr_migrate 8
write /proc/sys/kernel/sched_schedstats 0

# VM
write /proc/sys/vm/dirty_background_ratio 10
write /proc/sys/vm/dirty_ratio 30
write /proc/sys/vm/dirty_expire_centisecs 3000
write /proc/sys/vm/dirty_writeback_centisecs 3000
write /proc/sys/vm/page-cluster 0
write /proc/sys/vm/reap_mem_on_sigkill 1
write /proc/sys/vm/stat_interval 10
write /proc/sys/vm/swappiness 50
write /proc/sys/vm/overcommit_ratio 30
write /proc/sys/vm/vfs_cache_pressure 70

# Adreno_Idler 
write /sys/module/adreno_idler/parameters/adreno_idler_active Y
write /sys/module/adreno_idler/parameters/adreno_idler_downdifferential 24
write /sys/module/adreno_idler/parameters/adreno_idler_idlewait 15
write /sys/module/adreno_idler/parameters/adreno_idler_idleworkload 5000

# GPU
write /sys/devices/soc/5000000.qcom,kgsl-3d0/devfreq/5000000.qcom,kgsl-3d0/adrenoboost 3
write /sys/devices/soc/5000000.qcom,kgsl-3d0/kgsl/kgsl-3d0/throttling 0

# Raid
write /proc/sys/dev/raid/speed_limit_min 7000

# Pty
write /proc/sys/kernel/pty/max 4096

# GC_delay
write /proc/sys/kernel/keys/gc_delay 100
write /proc/sys/kernel/keys/maxbytes 20000
write /proc/sys/kernel/keys/maxkeys 200

#break_time
write /proc/sys/fs/lease-break-time 5
write /proc/sys/fs/leases-enable 1

#sched_domain
write /proc/sys/kernel/sched_domain/cpu0/domain0/min_interval 2
write /proc/sys/kernel/sched_domain/cpu0/domain1/min_interval 8
write /proc/sys/kernel/sched_domain/cpu1/domain0/min_interval 2
write /proc/sys/kernel/sched_domain/cpu1/domain1/min_interval 8
write /proc/sys/kernel/sched_domain/cpu2/domain0/min_interval 2
write /proc/sys/kernel/sched_domain/cpu2/domain1/min_interval 8
write /proc/sys/kernel/sched_domain/cpu3/domain0/min_interval 2
write /proc/sys/kernel/sched_domain/cpu3/domain1/min_interval 8
write /proc/sys/kernel/sched_domain/cpu4/domain0/min_interval 2
write /proc/sys/kernel/sched_domain/cpu4/domain1/min_interval 8
write /proc/sys/kernel/sched_domain/cpu5/domain0/min_interval 2
write /proc/sys/kernel/sched_domain/cpu5/domain1/min_interval 8
write /proc/sys/kernel/sched_domain/cpu6/domain0/min_interval 2
write /proc/sys/kernel/sched_domain/cpu6/domain1/min_interval 8
write /proc/sys/kernel/sched_domain/cpu7/domain0/min_interval 2
write /proc/sys/kernel/sched_domain/cpu7/domain1/min_interval 8
write /proc/sys/kernel/sched_domain/cpu0/domain0/busy_factor 32
write /proc/sys/kernel/sched_domain/cpu1/domain0/busy_factor 32
write /proc/sys/kernel/sched_domain/cpu2/domain0/busy_factor 32
write /proc/sys/kernel/sched_domain/cpu3/domain0/busy_factor 32
write /proc/sys/kernel/sched_domain/cpu4/domain0/busy_factor 32
write /proc/sys/kernel/sched_domain/cpu5/domain0/busy_factor 32
write /proc/sys/kernel/sched_domain/cpu6/domain0/busy_factor 32
write /proc/sys/kernel/sched_domain/cpu7/domain0/busy_factor 32
write /proc/sys/kernel/sched_domain/cpu0/domain0/busy_idx 2
write /proc/sys/kernel/sched_domain/cpu1/domain0/busy_idx 2
write /proc/sys/kernel/sched_domain/cpu2/domain0/busy_idx 2
write /proc/sys/kernel/sched_domain/cpu3/domain0/busy_idx 2
write /proc/sys/kernel/sched_domain/cpu4/domain0/busy_idx 2
write /proc/sys/kernel/sched_domain/cpu5/domain0/busy_idx 2
write /proc/sys/kernel/sched_domain/cpu6/domain0/busy_idx 2
write /proc/sys/kernel/sched_domain/cpu7/domain0/busy_idx 2
write /proc/sys/kernel/sched_domain/cpu0/domain0/cache_nice_tries 1
write /proc/sys/kernel/sched_domain/cpu1/domain0/cache_nice_tries 1
write /proc/sys/kernel/sched_domain/cpu2/domain0/cache_nice_tries 1
write /proc/sys/kernel/sched_domain/cpu3/domain0/cache_nice_tries 1
write /proc/sys/kernel/sched_domain/cpu4/domain0/cache_nice_tries 1
write /proc/sys/kernel/sched_domain/cpu5/domain0/cache_nice_tries 1
write /proc/sys/kernel/sched_domain/cpu6/domain0/cache_nice_tries 1
write /proc/sys/kernel/sched_domain/cpu7/domain0/cache_nice_tries 1
write /proc/sys/kernel/sched_domain/cpu0/domain0/flags 4143
write /proc/sys/kernel/sched_domain/cpu1/domain0/flags 4143
write /proc/sys/kernel/sched_domain/cpu2/domain0/flags 4143
write /proc/sys/kernel/sched_domain/cpu3/domain0/flags 4143
write /proc/sys/kernel/sched_domain/cpu4/domain0/flags 4143
write /proc/sys/kernel/sched_domain/cpu5/domain0/flags 4143
write /proc/sys/kernel/sched_domain/cpu6/domain0/flags 4143
write /proc/sys/kernel/sched_domain/cpu7/domain0/flags 4143
write /proc/sys/kernel/sched_domain/cpu0/domain0/forkexec_idx 0
write /proc/sys/kernel/sched_domain/cpu1/domain0/forkexec_idx 0
write /proc/sys/kernel/sched_domain/cpu2/domain0/forkexec_idx 0
write /proc/sys/kernel/sched_domain/cpu3/domain0/forkexec_idx 0
write /proc/sys/kernel/sched_domain/cpu4/domain0/forkexec_idx 0
write /proc/sys/kernel/sched_domain/cpu5/domain0/forkexec_idx 0
write /proc/sys/kernel/sched_domain/cpu6/domain0/forkexec_idx 0
write /proc/sys/kernel/sched_domain/cpu7/domain0/forkexec_idx 0
write /proc/sys/kernel/sched_domain/cpu0/domain0/idle_idx 1
write /proc/sys/kernel/sched_domain/cpu1/domain0/idle_idx 1
write /proc/sys/kernel/sched_domain/cpu2/domain0/idle_idx 1
write /proc/sys/kernel/sched_domain/cpu3/domain0/idle_idx 1
write /proc/sys/kernel/sched_domain/cpu4/domain0/idle_idx 1
write /proc/sys/kernel/sched_domain/cpu5/domain0/idle_idx 1
write /proc/sys/kernel/sched_domain/cpu6/domain0/idle_idx 1
write /proc/sys/kernel/sched_domain/cpu7/domain0/idle_idx 1
write /proc/sys/kernel/sched_domain/cpu0/domain0/imbalance_pct 125
write /proc/sys/kernel/sched_domain/cpu1/domain0/imbalance_pct 125
write /proc/sys/kernel/sched_domain/cpu2/domain0/imbalance_pct 125
write /proc/sys/kernel/sched_domain/cpu3/domain0/imbalance_pct 125
write /proc/sys/kernel/sched_domain/cpu4/domain0/imbalance_pct 125
write /proc/sys/kernel/sched_domain/cpu5/domain0/imbalance_pct 125
write /proc/sys/kernel/sched_domain/cpu6/domain0/imbalance_pct 125
write /proc/sys/kernel/sched_domain/cpu7/domain0/imbalance_pct 125
write /proc/sys/kernel/sched_domain/cpu0/domain0/max_interval 4
write /proc/sys/kernel/sched_domain/cpu1/domain0/max_interval 4
write /proc/sys/kernel/sched_domain/cpu2/domain0/max_interval 4
write /proc/sys/kernel/sched_domain/cpu3/domain0/max_interval 4
write /proc/sys/kernel/sched_domain/cpu4/domain0/max_interval 4
write /proc/sys/kernel/sched_domain/cpu5/domain0/max_interval 4
write /proc/sys/kernel/sched_domain/cpu6/domain0/max_interval 4
write /proc/sys/kernel/sched_domain/cpu7/domain0/max_interval 4
write /proc/sys/kernel/sched_domain/cpu0/domain0/newidle_idx 0
write /proc/sys/kernel/sched_domain/cpu1/domain0/newidle_idx 0
write /proc/sys/kernel/sched_domain/cpu2/domain0/newidle_idx 0
write /proc/sys/kernel/sched_domain/cpu3/domain0/newidle_idx 0
write /proc/sys/kernel/sched_domain/cpu4/domain0/newidle_idx 0
write /proc/sys/kernel/sched_domain/cpu5/domain0/newidle_idx 0
write /proc/sys/kernel/sched_domain/cpu6/domain0/newidle_idx 0
write /proc/sys/kernel/sched_domain/cpu7/domain0/newidle_idx 0
write /proc/sys/kernel/sched_domain/cpu0/domain0/wake_idx 0
write /proc/sys/kernel/sched_domain/cpu1/domain0/wake_idx 0
write /proc/sys/kernel/sched_domain/cpu2/domain0/wake_idx 0
write /proc/sys/kernel/sched_domain/cpu3/domain0/wake_idx 0
write /proc/sys/kernel/sched_domain/cpu4/domain0/wake_idx 0
write /proc/sys/kernel/sched_domain/cpu5/domain0/wake_idx 0
write /proc/sys/kernel/sched_domain/cpu6/domain0/wake_idx 0
write /proc/sys/kernel/sched_domain/cpu7/domain0/wake_idx 0

# Wakeup_threshold
write /proc/sys/kernel/random/read_wakeup_threshold 16
write /proc/sys/kernel/random/write_wakeup_threshold 16
write /proc/sys/kernel/random/urandom_min_reseed_secs 120

# Stune_Boost
write /sys/module/cpu_boost/parameters/dynamic_stune_boost 15
write /sys/module/cpu_boost/parameters/dynamic_stune_boost_ms 500
write /sys/module/cpu_boost/parameters/input_boost_freq 0:0 1:0 2:0 3:0 4:0 5:0 6:0 7:0 
write /sys/module/cpu_boost/parameters/input_boost_ms 30

# Uclamp
write /proc/sys/kernel/sched_util_clamp_min 128
write /proc/sys/kernel/sched_util_clamp_min_rt_default 128
write /dev/cpuset/top-app/uclamp.max max
write /dev/cpuset/top-app/uclamp.min 50
write /dev/cpuset/top-app/uclamp.boosted 1
write /dev/cpuset/top-app/uclamp.latency_sensitive 1
write /dev/cpuset/foreground/uclamp.max 50
write /dev/cpuset/foreground/uclamp.min 20
write /dev/cpuset/foreground/uclamp.boosted 0
write /dev/cpuset/foreground/uclamp.latency_sensitive 0
write /dev/cpuset/background/uclamp.max 50
write /dev/cpuset/background/uclamp.min 10
write /dev/cpuset/background/uclamp.boosted 0
write /dev/cpuset/background/uclamp.latency_sensitive 0
write /dev/cpuset/system-background/uclamp.max 50
write /dev/cpuset/system-background/uclamp.min 10
write /dev/cpuset/system-background/uclamp.boosted 0
write /dev/cpuset/system-background/uclamp.latency_sensitive 0

# CPU
for cpu in /sys/devices/system/cpu/cpu*/cpufreq/
do
	avail_govs="$(cat "${cpu}scaling_available_governors")"
	if [[ "$avail_govs" == *"schedutil"* ]]
	then
		write "${cpu}scaling_governor" schedutil
		write "${cpu}schedutil/up_rate_limit_us" 0
		write "${cpu}schedutil/down_rate_limit_us" 0
		write "${cpu}schedutil/rate_limit_us" 0
		write "${cpu}schedutil/hispeed_load" 90
		write "${cpu}schedutil/hispeed_freq" "$(cat "${cpu}cpuinfo_max_freq")"
	fi
done

# I/O
for queue in /sys/block/*/queue/
do
	avail_scheds="$(cat "${queue}scheduler")"
	for sched in cfq anxiety noop kyber bfq mq-deadline none
	do
		if [[ "$avail_scheds" == *"$sched"* ]]
		then
			write "${queue}scheduler" "$sched"
			break
		fi
	done
	write "${queue}iostats" 0
	write "${queue}read_ahead_kb" 512
	write "${queue}nr_requests" 128
done

exit 0
